// GENERATED by scripts/gen-regression-registries.mjs — do not edit.
import Accordion from "@xtyle/astro/Accordion.astro";
import Alert from "@xtyle/astro/Alert.astro";
import AppShell from "@xtyle/astro/AppShell.astro";
import Avatar from "@xtyle/astro/Avatar.astro";
import AvatarGroup from "@xtyle/astro/AvatarGroup.astro";
import Badge from "@xtyle/astro/Badge.astro";
import Bar from "@xtyle/astro/Bar.astro";
import BottomNav from "@xtyle/astro/BottomNav.astro";
import Breadcrumb from "@xtyle/astro/Breadcrumb.astro";
import Button from "@xtyle/astro/Button.astro";
import Calendar from "@xtyle/astro/Calendar.astro";
import Card from "@xtyle/astro/Card.astro";
import CardLink from "@xtyle/astro/CardLink.astro";
import Carousel from "@xtyle/astro/Carousel.astro";
import Chart from "@xtyle/astro/Chart.astro";
import Checkbox from "@xtyle/astro/Checkbox.astro";
import Cluster from "@xtyle/astro/Cluster.astro";
import Code from "@xtyle/astro/Code.astro";
import ColorPicker from "@xtyle/astro/ColorPicker.astro";
import Combobox from "@xtyle/astro/Combobox.astro";
import CommandPalette from "@xtyle/astro/CommandPalette.astro";
import DatePicker from "@xtyle/astro/DatePicker.astro";
import Dialog from "@xtyle/astro/Dialog.astro";
import Dock from "@xtyle/astro/Dock.astro";
import DockZone from "@xtyle/astro/DockZone.astro";
import Dot from "@xtyle/astro/Dot.astro";
import Dropzone from "@xtyle/astro/Dropzone.astro";
import Empty from "@xtyle/astro/Empty.astro";
import Eyebrow from "@xtyle/astro/Eyebrow.astro";
import Field from "@xtyle/astro/Field.astro";
import FormGroup from "@xtyle/astro/FormGroup.astro";
import Grid from "@xtyle/astro/Grid.astro";
import Heading from "@xtyle/astro/Heading.astro";
import Heatmap from "@xtyle/astro/Heatmap.astro";
import Hero from "@xtyle/astro/Hero.astro";
import Icon from "@xtyle/astro/Icon.astro";
import Image from "@xtyle/astro/Image.astro";
import Kbd from "@xtyle/astro/Kbd.astro";
import Link from "@xtyle/astro/Link.astro";
import List from "@xtyle/astro/List.astro";
import Markdown from "@xtyle/astro/Markdown.astro";
import Menu from "@xtyle/astro/Menu.astro";
import MobileShell from "@xtyle/astro/MobileShell.astro";
import NumberInput from "@xtyle/astro/NumberInput.astro";
import Pagination from "@xtyle/astro/Pagination.astro";
import Panel from "@xtyle/astro/Panel.astro";
import Parallax from "@xtyle/astro/Parallax.astro";
import Pie from "@xtyle/astro/Pie.astro";
import Popover from "@xtyle/astro/Popover.astro";
import Progress from "@xtyle/astro/Progress.astro";
import Qr from "@xtyle/astro/Qr.astro";
import Radio from "@xtyle/astro/Radio.astro";
import Rating from "@xtyle/astro/Rating.astro";
import Redact from "@xtyle/astro/Redact.astro";
import Ribbon from "@xtyle/astro/Ribbon.astro";
import Section from "@xtyle/astro/Section.astro";
import Segmented from "@xtyle/astro/Segmented.astro";
import Select from "@xtyle/astro/Select.astro";
import Separator from "@xtyle/astro/Separator.astro";
import Sheet from "@xtyle/astro/Sheet.astro";
import Skeleton from "@xtyle/astro/Skeleton.astro";
import Slider from "@xtyle/astro/Slider.astro";
import Sparkline from "@xtyle/astro/Sparkline.astro";
import Spinner from "@xtyle/astro/Spinner.astro";
import SplitButton from "@xtyle/astro/SplitButton.astro";
import Splitter from "@xtyle/astro/Splitter.astro";
import Spotlight from "@xtyle/astro/Spotlight.astro";
import Stack from "@xtyle/astro/Stack.astro";
import Stat from "@xtyle/astro/Stat.astro";
import Statusbar from "@xtyle/astro/Statusbar.astro";
import Steps from "@xtyle/astro/Steps.astro";
import Swatch from "@xtyle/astro/Swatch.astro";
import Switch from "@xtyle/astro/Switch.astro";
import Table from "@xtyle/astro/Table.astro";
import Tabs from "@xtyle/astro/Tabs.astro";
import Text from "@xtyle/astro/Text.astro";
import Textarea from "@xtyle/astro/Textarea.astro";
import Timeline from "@xtyle/astro/Timeline.astro";
import Toast from "@xtyle/astro/Toast.astro";
import Toc from "@xtyle/astro/Toc.astro";
import Toolbar from "@xtyle/astro/Toolbar.astro";
import Tooltip from "@xtyle/astro/Tooltip.astro";
import Tour from "@xtyle/astro/Tour.astro";
import Tree from "@xtyle/astro/Tree.astro";

export const astroRegistry: Record<string, unknown> = {
	"accordion": Accordion,
	"alert": Alert,
	"app-shell": AppShell,
	"avatar": Avatar,
	"avatar-group": AvatarGroup,
	"badge": Badge,
	"bar": Bar,
	"bottom-nav": BottomNav,
	"breadcrumb": Breadcrumb,
	"button": Button,
	"calendar": Calendar,
	"card": Card,
	"card-link": CardLink,
	"carousel": Carousel,
	"chart": Chart,
	"checkbox": Checkbox,
	"cluster": Cluster,
	"code": Code,
	"color-picker": ColorPicker,
	"combobox": Combobox,
	"command-palette": CommandPalette,
	"date-picker": DatePicker,
	"dialog": Dialog,
	"dock": Dock,
	"dock-zone": DockZone,
	"dot": Dot,
	"dropzone": Dropzone,
	"empty": Empty,
	"eyebrow": Eyebrow,
	"field": Field,
	"form-group": FormGroup,
	"grid": Grid,
	"heading": Heading,
	"heatmap": Heatmap,
	"hero": Hero,
	"icon": Icon,
	"image": Image,
	"kbd": Kbd,
	"link": Link,
	"list": List,
	"markdown": Markdown,
	"menu": Menu,
	"mobile-shell": MobileShell,
	"number-input": NumberInput,
	"pagination": Pagination,
	"panel": Panel,
	"parallax": Parallax,
	"pie": Pie,
	"popover": Popover,
	"progress": Progress,
	"qr": Qr,
	"radio": Radio,
	"rating": Rating,
	"redact": Redact,
	"ribbon": Ribbon,
	"section": Section,
	"segmented": Segmented,
	"select": Select,
	"separator": Separator,
	"sheet": Sheet,
	"skeleton": Skeleton,
	"slider": Slider,
	"sparkline": Sparkline,
	"spinner": Spinner,
	"split-button": SplitButton,
	"splitter": Splitter,
	"spotlight": Spotlight,
	"stack": Stack,
	"stat": Stat,
	"statusbar": Statusbar,
	"steps": Steps,
	"swatch": Swatch,
	"switch": Switch,
	"table": Table,
	"tabs": Tabs,
	"text": Text,
	"textarea": Textarea,
	"timeline": Timeline,
	"toast": Toast,
	"toc": Toc,
	"toolbar": Toolbar,
	"tooltip": Tooltip,
	"tour": Tour,
	"tree": Tree,
};
