import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { discoverAlgorithms, readAlgorithmManifest, writeStaticManifest } from "./algorithms.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const mods = discoverAlgorithms(root);

for (const mod of mods) {
	await build({
		entryPoints: [mod.sourcePath],
		outfile: mod.scriptPath,
		bundle: true,
		format: "iife",
		platform: "neutral",
		target: "es2020",
		legalComments: "none",
		logLevel: "warning",
	});
	console.log(`bundled ${mod.id} mod -> algorithms/${mod.dir}/src/mod.js`);
}

// The static manifest block: what each algorithm produces, the knobs it reads and their domains, its
// invariant count and pass names, stamped into the packaged mod manifest. Read off the *built* mod, so
// the block is the algorithm's own account of itself rather than a second one derived from the engine.
// A discovery index reads it without booting a sandbox per algorithm; the host cross-checks it against
// the code on the one load that already happens, so a stale block cannot pass itself off as current.
for (const mod of mods) {
	const block = readAlgorithmManifest(readFileSync(mod.scriptPath, "utf8"), mod.id);
	if (writeStaticManifest(mod, block)) {
		console.log(`stamped ${mod.id} static manifest -> algorithms/${mod.dir}/mod-manifest.json`);
	}
}

const core = join(root, "packages", "xtyle");

// The authoring prelude: the mod-side authoring helpers bundled into one IIFE that exposes them
// on the sandbox global scope, embedded as a string an author's import-free Tier-2 source is
// prepended to before `loadAlgorithm` runs it — so in-browser authoring needs no bundler.
const prelude = await build({
	entryPoints: [join(core, "src/host/authoring-prelude-entry.ts")],
	bundle: true,
	format: "iife",
	platform: "neutral",
	target: "es2020",
	write: false,
	legalComments: "none",
	logLevel: "warning",
});
writeFileSync(
	join(core, "src/host/authoring-prelude.generated.ts"),
	"// generated by scripts/build-mods.mjs: do not edit\n" +
		`export const authoringPrelude = ${JSON.stringify(prelude.outputFiles[0].text)};\n`,
);
console.log("bundled authoring prelude -> packages/xtyle/src/host/authoring-prelude.generated.ts");

await build({
	entryPoints: [join(core, "src/batteries.ts")],
	outfile: join(core, "dist/batteries.js"),
	bundle: true,
	format: "esm",
	platform: "neutral",
	target: "es2020",
	external: ["@xtyle/core", "@xtyle/core/*"],
	legalComments: "none",
	logLevel: "warning",
});
console.log("bundled batteries -> packages/xtyle/dist/batteries.js");

// The browser-delivery bundle: each mod's manifest + its built `mod.js`, embedded as data so a
// filesystem-free consumer (the browser) can load it through the neutral host without `node:fs`. The
// disk-reading resolver stays the Node path; this is its client-side twin over the same `loadAlgorithm`,
// discovered off the same scan, so the two can never disagree about which algorithms exist.
const bundles = {};
for (const mod of mods) {
	bundles[mod.id] = {
		manifest: JSON.parse(readFileSync(mod.manifestPath, "utf8")),
		source: readFileSync(mod.scriptPath, "utf8"),
	};
}
writeFileSync(
	join(core, "src/host/algorithms-bundle.generated.ts"),
	"// generated by scripts/build-mods.mjs: do not edit\n" +
		`export const ALGORITHM_BUNDLES: Record<string, { manifest: unknown; source: string }> = ${JSON.stringify(bundles)};\n`,
);
console.log(`bundled ${mods.length} mods for browser delivery -> packages/xtyle/src/host/algorithms-bundle.generated.ts`);
