import { build } from "esbuild";
import { readdirSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const modsDir = join(root, "algorithms");

const mods = readdirSync(modsDir, { withFileTypes: true })
	.filter((e) => e.isDirectory() && existsSync(join(modsDir, e.name, "src", "mod.ts")))
	.map((e) => e.name);

for (const id of mods) {
	const here = join(modsDir, id);
	await build({
		entryPoints: [join(here, "src/mod.ts")],
		outfile: join(here, "src/mod.js"),
		bundle: true,
		format: "iife",
		platform: "neutral",
		target: "es2020",
		legalComments: "none",
		logLevel: "warning",
	});
	console.log(`bundled ${id} mod -> algorithms/${id}/src/mod.js`);
}

const core = join(root, "packages", "xtyle");

// The authoring prelude: the mod-side authoring helpers bundled into one IIFE that exposes them
// on the sandbox global scope, embedded as a string an author's import-free Tier-2 source is
// prepended to before `loadAlgorithm` runs it — so in-browser authoring needs no bundler.
const prelude = await build({
	entryPoints: [join(core, "src/host/authoring-prelude-entry.ts")],
	bundle: true,
	format: "iife",
	platform: "neutral",
	target: "es2020",
	write: false,
	legalComments: "none",
	logLevel: "warning",
});
writeFileSync(
	join(core, "src/host/authoring-prelude.generated.ts"),
	"// generated by scripts/build-mods.mjs: do not edit\n" +
		`export const authoringPrelude = ${JSON.stringify(prelude.outputFiles[0].text)};\n`,
);
console.log("bundled authoring prelude -> packages/xtyle/src/host/authoring-prelude.generated.ts");

await build({
	entryPoints: [join(core, "src/batteries.ts")],
	outfile: join(core, "dist/batteries.js"),
	bundle: true,
	format: "esm",
	platform: "neutral",
	target: "es2020",
	external: ["@xtyle/core", "@xtyle/core/*"],
	legalComments: "none",
	logLevel: "warning",
});
console.log("bundled batteries -> packages/xtyle/dist/batteries.js");

// The browser-delivery bundle: each blessed mod's manifest + its built `mod.js`, embedded as data so a
// filesystem-free consumer (the browser) can load it through the neutral host without `node:fs`. The
// disk-reading resolver stays the Node path; this is its client-side twin over the same `loadAlgorithm`.
const bundles = {};
for (const id of mods) {
	const here = join(modsDir, id);
	bundles[id] = {
		manifest: JSON.parse(readFileSync(join(here, "mod-manifest.json"), "utf8")),
		source: readFileSync(join(here, "src/mod.js"), "utf8"),
	};
}
writeFileSync(
	join(core, "src/host/algorithms-bundle.generated.ts"),
	"// generated by scripts/build-mods.mjs: do not edit\n" +
		`export const ALGORITHM_BUNDLES: Record<string, { manifest: unknown; source: string }> = ${JSON.stringify(bundles)};\n`,
);
console.log(`bundled ${mods.length} mods for browser delivery -> packages/xtyle/src/host/algorithms-bundle.generated.ts`);
