import type { ComponentManifest } from "./types.js";

export const listManifest: ComponentManifest = {
	id: "list",
	name: "List",
	category: "content",
	since: "0.9.0",
	summary: "A navigable, optionally-selectable collection of items — the reference skin over the shared collection substrate.",
	description:
		"The plainest collection: a list of items you move a keyboard cursor across and optionally choose among. It is the reference skin over xtyle's shared collection core (roving navigation + the none/single/multi/range selection model + the item anatomy), the same core the specialized list-like components build on. Reach for it when you want a general list and none of the specialized identities (menu, tree, tabs, combobox).",
	keywords: ["listbox", "options", "select", "multiselect", "collection", "roving", "menu"],
	seeAlso: ["menu", "tree", "combobox", "segmented", "tabs"],
	bindings: ["html", "svelte", "astro"],
	anatomy: [
		{ name: "root", description: "The host container.", selector: ".xtyle-list-shell" },
		{ name: "list", description: "The list/listbox element holding the items.", selector: ".xtyle-list", tokens: ["--space-1", "--font-sans", "--text-body", "--fg-1"] },
		{ name: "item", description: "One row: lead, content, trail, and (when actionable) actions.", selector: ".xtyle-list__item", tokens: ["--space-2", "--space-3", "--radius-sm", "--state-hover", "--accent-bg", "--fg-0", "--fg-disabled"] },
		{ name: "lead", description: "A leading icon.", selector: ".xtyle-list__lead", tokens: ["--fg-2"] },
		{ name: "label", description: "The item's primary text.", selector: ".xtyle-list__label" },
		{ name: "trail", description: "Trailing text: a shortcut, count, or badge.", selector: ".xtyle-list__trail", tokens: ["--fg-2", "--text-sm"] },
		{ name: "actions", description: "The per-item action cluster (actionable posture); each button emits a list-action event.", selector: ".xtyle-list__actions" },
	],
	props: [
		{ name: "items", type: "string | (string | ListItem)[]", description: "The items, as a comma-string shorthand (label:value pairs or bare labels) or a structured array carrying lead/trail/actions. Also accepts a JSON string on the attribute.", bindings: ["html", "svelte", "astro"] },
		{ name: "interaction", type: "\"static\" | \"navigational\" | \"selectable\" | \"actionable\"", default: "navigational", description: "The interaction posture: presentational, keyboard-navigable, selectable, or navigable with per-item actions.", bindings: ["html", "svelte", "astro"], options: ["static", "navigational", "selectable", "actionable"] },
		{ name: "selection", type: "\"none\" | \"single\" | \"multi\" | \"range\"", default: "none", description: "The selection model (only meaningful under interaction=\"selectable\"). Ctrl/Cmd-click toggles, Shift-click extends a range.", bindings: ["html", "svelte", "astro"], options: ["none", "single", "multi", "range"] },
		{ name: "orientation", type: "\"vertical\" | \"horizontal\"", default: "vertical", description: "The list flow and the roving arrow-key axis.", bindings: ["html", "svelte", "astro"], options: ["vertical", "horizontal"] },
		{ name: "size", type: "\"sm\" | \"md\" | \"lg\"", default: "md", description: "The item type scale.", bindings: ["html", "svelte", "astro"], options: ["sm", "md", "lg"] },
		{ name: "label", type: "string", description: "A visible group label; use labelledby or aria-label instead where a visible label would be noise.", bindings: ["html", "svelte", "astro"] },
	],
	variants: [],
	sizes: [
		{ name: "sm", description: "Compact rows.", className: "xtyle-list--sm" },
		{ name: "md", description: "Default rows.", className: "xtyle-list--md", isDefault: true },
		{ name: "lg", description: "Roomy rows.", className: "xtyle-list--lg" },
	],
	states: [
		{ name: "active", description: "The item under the roving keyboard cursor (focus), distinct from selection.", selector: ".xtyle-list__item:focus-visible", tokens: ["--accent", "--border-normal"] },
		{ name: "selected", description: "A chosen item, marked with an accent fill and, under --selection-cue: marker, a redundant check.", selector: ".xtyle-list__item[aria-selected=\"true\"]", tokens: ["--accent-bg", "--fg-0", "--selection-cue"] },
		{ name: "disabled", description: "A non-interactive item, skipped by roving.", selector: ".xtyle-list__item[aria-disabled=\"true\"]", tokens: ["--fg-disabled"] },
	],
	slots: [],
	consumedTokens: [
		"--accent",
		"--accent-bg",
		"--border-normal",
		"--fg-0",
		"--fg-1",
		"--fg-2",
		"--fg-disabled",
		"--font-sans",
		"--radius-sm",
		"--selection-cue",
		"--space-1",
		"--space-2",
		"--space-3",
		"--state-hover",
		"--text-body",
		"--text-lg",
		"--text-sm",
		"--weight-medium",
		"--weight-semibold",
	],
	composition: [
		"Built on the collection substrate: the roving navigation, selection model, and item anatomy are the same core the menu, tree, tabs, segmented, combobox, command-palette, and pagination components share.",
	],
	a11y: [
		"A selectable list is a role=listbox of role=option items with aria-selected; multi and range add aria-multiselectable. A non-selectable list is role=list of role=listitem.",
		"Roving tabindex: exactly one item is in the tab order; arrow keys move the cursor, Home/End jump to the ends. Focus (the roving cursor) is kept distinct from selection.",
		"Selection is never color-only: under --selection-cue: marker the selected item gains a redundant check.",
		"Provide a label, labelledby, or aria-label so the list is announced.",
	],
	examples: [
		{
			id: "selectable-single",
			title: "Single-select",
			description: "A listbox where one item is chosen at a time.",
			source: {
				html: '<xtyle-list label="Plan" interaction="selectable" selection="single" items="Starter,Pro,Team"></xtyle-list>',
				astro: '<List label="Plan" interaction="selectable" selection="single" items="Starter,Pro,Team" />',
				svelte: '<List label="Plan" interaction="selectable" selection="single" items="Starter,Pro,Team" />',
			},
		},
		{
			id: "selectable-multi",
			title: "Multi-select",
			description: "Ctrl/Cmd-click toggles items; Shift-click (with selection=\"range\") extends a span.",
			source: {
				html: '<xtyle-list label="Toppings" interaction="selectable" selection="multi" items="Cheese,Basil,Chili,Olives"></xtyle-list>',
				astro: '<List label="Toppings" interaction="selectable" selection="multi" items="Cheese,Basil,Chili,Olives" />',
				svelte: '<List label="Toppings" interaction="selectable" selection="multi" items="Cheese,Basil,Chili,Olives" />',
			},
		},
	],
};
