name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: rm -f package-lock.json && npm install
      - run: npm run build

      - name: publish core
        continue-on-error: true
        run: npm publish --workspace=packages/xtyle --access public

      - name: publish svelte
        continue-on-error: true
        run: npm publish --workspace=packages/svelte --access public

      - name: publish astro
        continue-on-error: true
        run: npm publish --workspace=packages/astro --access public
